LinkShortener/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ShortLinks.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

ShortLinks/urls.py
from django.urls import path
from . import views
from ShortLinks.Views.Auth import Login, Register
from ShortLinks.Views.Statistics import Statistics
from django.contrib.auth import views as auth_views

app_name = 'ShortLinks'


urlpatterns = [
    path('', views.Index.as_view(), name='home'),
    path('<str:urlId>', views.RedirectUrl.as_view(), name='redirect'),
    path('home/statistics', Statistics.Statistics.as_view(), name='statistics'),
    path('home/create', views.CreateShortLink.as_view(), name='create'),

    path('login/', Login.Login.as_view(), name='login'),
    path('register/', Register.Register.as_view(), name='register'),
    path('profile/', views.Profile.as_view(), name='profile'),

    #Some Functions
    path('logout/', Login.logout_view, name='logout'),

    # path('home/', views.home, name='home'),
    # path('login/', auth_views.login, name='login'),
]

ShortLinks/models.py
from django.contrib.auth.models import User, AnonymousUser
from django.db import models
from django.utils import timezone

from LinkShortener.globalVariables import *

# Create your models here.


class ShortLink(models.Model):
    ShortLinkId = models.CharField(max_length=200)
    LongLinkValue = models.CharField(max_length=5000)
    CreationDate = models.DateTimeField('Creation Date')
    ExpirationDate = models.DateTimeField('Expiration Date', default=timezone.now)
    TimesUsed = models.BigIntegerField(default=0)
    CreatedBy = models.ForeignKey(User, on_delete=models.CASCADE, default=3)

    def __str__(self):
        return '{0} : {1} : {2}'.format(self.ShortLinkId, self.LongLinkValue, self.CreatedBy_id)

    class Meta:
        ordering = ['-CreationDate']

ShortLinks/forms.py
from django.forms import forms


class LoginForm(forms.Form):
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Login'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

ShortLinks/views.py
from datetime import datetime

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, Http404
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

from ShortLinks.Helpers import Helpers
from ShortLinks.ViewModels.IndexViewModel import IndexViewModel
from ShortLinks.ViewModels.ProfileViewModel import ProfileViewModel
from .models import ShortLink
from ShortLinks.Respositories.ShortLinksRepository import ShortLinksRepository

# Create your views here.


from django.contrib.auth.decorators import login_required
from django.shortcuts import render

class Index(View):
    templateName = 'ShortLinks/Index/index.html'

    def get(self, request):
        lastTenUrls = ShortLink.objects.order_by('CreationDate')\
            .filter(ExpirationDate__gt=timezone.now(), CreatedBy__id=3)[:10]

        model = IndexViewModel
        model.links = lastTenUrls
        model.host = Helpers.getAbsoluteUrl(request)
        if 'error' in request.session:
            model.error = request.session['error']
            request.session['error'] = None
        context = {'model': model}
        return render(request, self.templateName, context)


class RedirectUrl(View):

    def get(self, request, urlId):
        try:
            shortLink = ShortLink.objects.get(ShortLinkId=urlId)
        except ShortLink.DoesNotExist:
            raise Http404('Link does not exist')

        shortLink.TimesUsed += 1
        shortLink.save()
        return HttpResponseRedirect(shortLink.LongLinkValue)


class CreateShortLink(View):
    def post(self, request):
        from ShortLinks.Services.ShortLinksService import ShortLinksService

        longLink = request.POST['LongLinkValue']
        from pytz import utc
        expirationDate = datetime.strptime(request.POST.get('expirationDate', '0001/01/01 00:00'), "%Y/%m/%d %H:%M").astimezone(utc)
        private = request.POST.get('private')

        next = request.POST.get('next', '/')

        try:
            ShortLinksService.createShortLink(longLink, expirationDate, request.user, private)
        except Exception as e:
            request.session['error'] = str(e)
            return redirect(next)

        return redirect(next)


def details(request, urlId):
    shortUrl = ShortLink.objects.get(ShortLinkId=urlId)
    context = {'shortUrl': shortUrl}
    return render(request, 'ShortLinks/details.html', context)


class Profile(LoginRequiredMixin, View):
    print('Admin_View')
    login_url = '/login/'
    templateName = 'ShortLinks/Profile/profile.html'

    def get(self, request):
        links = ShortLinksRepository.getAllLinksFor(request.user)

        model = ProfileViewModel
        model.host = Helpers.getAbsoluteUrl(request)
        model.links = links

        context = {'model': model}
        return render(request, self.templateName, context)

    # def post(self, request):
    #     return redirect('ShortLinks:profile')

templates/ShortLinks/CreateNewAndListLinks.html
{% block content %}
<div class="row">
    <div class="col s8 middle">
        <div class="row flexbox middle">
            <div class="middle col s6 min-w25">
                {% include "ShortLinks/Index/FastLinkCreate.html" with error=model.error %}
            </div>
    
            <div class="middle col s5 min-w25">
                {% include "ShortLinks/Index/LinksList.html" with links=model.links host=model.host %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/ShortLinks/Global/NavBar.html
{% block navBar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand mb-0 h1" href="/">Link Shortener</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ShortLinks:statistics' %}">Statistics</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Not Implemented yet</a>
                </li>
            </ul>
        <div class="form-inline">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ShortLinks:profile' %}">{% if user.is_authenticated %}{{ user.username }}{% else %}Profile{% endif %}</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ShortLinks:logout' %}">Logout</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        </div>
    </nav>
{% endblock %}

templates/ShortLinks/Global/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block  title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'ShortLinks/bootstrap/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'ShortLinks/styles.css' %}"/>
</head>
<body class="blue-grey lighten-4">
<script src="{% static 'ShortLinks/variables.js' %}"></script>

{% include 'ShortLinks/Global/NavBar.html' %}

<div class="middle">
    {% block content %}
    {% endblock %}
</div>

<script defer src="{% static 'ShortLinks/jquery-3.3.1.min.js' %}"></script>
<script defer src="{% static 'ShortLinks/bootstrap/js/bootstrap.min.js' %}"></script>
<script defer src="{% static 'ShortLinks/js/Velocity.min.js' %}"></script>
<script async src="{% static 'ShortLinks/js/index.js' %}"></script>
</body>
</html>

templates/ShortLinks/Index/FastLinkCreate.html
{% load static %}
<link rel="stylesheet" href="{% static 'ShortLinks/bootstrap/datepicker/jquery.datetimepicker.min.css' %}">

<div class="card">
    <div class="card-body">
        <h5 class="card-title">Create new link</h5>
        <p class="card-text">The new short link will be created by supplying the source link and the time to live for
            the link.</p>
        {% if error %}
            <h5 class="text-danger">{{ error }}</h5>
        {% endif %}
    </div>
    <form action="{% url 'ShortLinks:create' %}" method="post">
        {% csrf_token %}
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="LongLinkValue" placeholder="Link to shorten"
                           id="LongLinkValue" autocomplete="off"/>
                </div>
                <div class="input-group mb-3">
                    <input id="datetimepicker" name="expirationDate" class="form-control" type="text"
                           placeholder="Expiration date" autocomplete="off" required>
                </div>
                {% if not user.is_anonymous %}
                    <div class="input-group mb-3">
                        <button id="privateCheckboxButton" type="button" class="btn">
                            <i class="fas fa-lock-open"></i>
                            <i class="fas fa-lock" hidden></i>
                            Private
                        </button>
                        <input type="checkbox" hidden id="privateCheckbox" name="private">
                    </div>
                {% endif %}
                <input type="submit" class="btn btn-primary" value="Create"/>
            </li>
        </ul>
    </form>

    <script src="{% static 'ShortLinks/js/jquery2.1.4.min.js' %}"></script>
    <script src="{% static 'ShortLinks/bootstrap/datepicker/jquery.datetimepicker.full.min.js' %}"></script>
    <script src="{% static 'ShortLinks/js/Datetimepicker.js' %}"></script>
    <script src="{% static 'ShortLinks/js/NewLinkCreator.js' %}"></script>
</div>

templates/ShortLinks/Index/LinksList.html
{% if links %}
    {% for url in links %}
        {% include 'ShortLinks/details.html' with url=url %}
    {% endfor %} {% else %}
    <div class="card">
        <div class="card-content white-text">
            <span class="card-title">No links available.</span>
        </div>
    </div>

{% endif %}

templates/ShortLinks/Index/index.html
{% extends "ShortLinks/Global/layout.html" %}
{% load static %}
 {% block content %}
    {% include "ShortLinks/CreateNewAndListLinks.html" with model=model %}
{% endblock %}

templates/ShortLinks/Profile/profile.html
{% extends 'ShortLinks/Global/layout.html' %}

{% block content %}
    {% include "ShortLinks/CreateNewAndListLinks.html" with model=model %}
{% endblock %}

templates/ShortLinks/Statistics/Statistics.html
{% extends 'ShortLinks/Global/layout.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'ShortLinks/bootstrap/datepicker/jquery.datetimepicker.min.css' %}">

    <div class="flex-row">
    <div class="w6 middle">
        <div class="flex-row my-3">
            <ul class="list-group">
              <li class="list-group-item">
                  <div class="d-flex flex-row flex-justify-between font-weight-bold">
                      <div>
                          <span class="text-success">Total short links: </span>
                          {{ model.totalShortLinksCount }}
                      </div>
                      <div>
                          <span class="text-primary">Currently active links: </span>
                          {{ model.currentlyActiveLinksCount }}
                      </div>
                  </div>
              </li>
            </ul>
        </div>

        <div class="flex-row my-3">
            <ul class="list-group">
                <li class="list-group-item">
                    <div class="input-group">
                        <form action="" method="post" class="w10">
                            {% csrf_token %}
{#                      <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2">#}
                          <input id="datetimepicker" name="finalDate" class="form-control" type="text" placeholder="Pick date and time" autocomplete="off">
                            <small id="emailHelp" class="form-text text-muted">Get links that will expire by certain date.</small>
{#                          <div class="input-group-append">#}
                            <button type="submit" class="btn btn-primary">Filter</button>
{#                          </div>#}
                        </form>
                    </div>
                    {% if model.datetime is not None %}
                        <p>Displaying links that will become unavailable on <span class="font-weight-bold">{{ model.datetime }}</span></p>
                    {% endif %}
                </li>
            </ul>
        </div>

        <div class="flex-row">
            <div class="flex-column">
                <ul class="list-group">
                    {% for link in model.links %}
                        {% include 'ShortLinks/Statistics/StatisticsDetails.html' with link=link host=model.host%}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="{% static 'ShortLinks/bootstrap/datepicker/jquery.datetimepicker.full.min.js' %}"></script>
    <script src="{% static 'ShortLinks/js/Datetimepicker.js' %}"></script>
{% endblock %}

templates/ShortLinks/Statistics/StatisticsDetails.html
{#{% load tz %}#}
{% load linkTTLLeft from Filters %}
{#{% block content %}#}
{% load static %}
<link rel="stylesheet" href="{% static 'ShortLinks/css/Statistics/StatisticsDetails.css'%}">
 <li class="list-group-item">
     <div class="d-flex flex-row flex-justify-between link-details">
{#     <p></p>#}
{#     <p></p>#}
{#     <p></p>#}
{#     <p></p>#}
{#     <p></p>#}
        <div>
            <span>Short link: </span>
            <span>
                {{ link.ShortLinkId }}

            </span>
        </div>
        <div>
            {% if link.CreatedBy == request.user %}
                <i class="fas fa-lock"></i>
            {% endif %}
        </div>
        <div>
            <i class="far fa-clipboard" onclick="copyToClipboard('{{ host }}/{{ link.ShortLinkId }}')"></i>
        </div>

        <div>
            <span>{{ link.ExpirationDate|linkTTLLeft }}</span>
        </div>

        <div class="font-weight-bold text-primary w2">
            <span>Used {{ link.TimesUsed }} times.</span>
        </div>
     </div>
 </li>

templates/ShortLinks/details.html
{% load tz %}
{% load linkTTLLeft from Filters %}

{#```Requires host:str and url:ShortLink```#}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h5 id="{{ url.ShortLinkId }}" class="card-title">
                {{ url.ShortLinkId }}
                <i class="far fa-clipboard" onclick="copyToClipboard('{{ host }}/{{ url.ShortLinkId }}')"></i>
                <span></span>
            </h5>
            <h6 class="card-subtitle mb-2">Original Link:</h6>
            <p class="card-text"><a href="{{ url.LongLinkValue }}">{{ url.LongLinkValue }}</a></p>
        </div>
        <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a><span class=""><strong><span class="text-success">Time left: </span>{{ url.ExpirationDate|linkTTLLeft }}</strong></span></a>
                </li>
                <li class="list-group-item">
                    <a><span class=""><strong><span class="text-primary">Used:</span> {{ url.TimesUsed }} times</strong></span></a>
                </li>
              </ul>
    </div>
{% endblock %}